#!/bin/sh

# Update apt
apt update
# piwheels' version of cffi depends on libffi7 (our distro ships with libffi8)
apt -y install libffi7
ldconfig

# Create local python environment (we use `echo ""` as a noop)
poetry run echo ""

### Link certain dependencies to the system-wide version. These dependencies
### can't install or run properly when installed through poetry.
# PyQt5 5.15.1 fails during install:
#     AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
ln -sf /usr/lib/python3.9/site-packages/PyQt5* .venv/lib/python3.9/site-packages/
# cryptography fails at runtime:
#     ImportError: /home/root/projects/wright/.venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: EVP_PBE_scrypt, version OPENSSL_1_1_0
ln -sf /usr/lib/python3.9/site-packages/cryptography* .venv/lib/python3.9/site-packages/

# Install the remaining dependencies
poetry install -E gui
